name: GitHub Metrics
on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          user: zyqVizzzzz
          token: ${{ secrets.METRICS_TOKEN }}
          output_path: github-metrics.svg
          # template: classic
          base: header, activity, community, repositories

          base_indepth: false
          base_hireable: false
          base_skip: false
          plugin_languages: true
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_other: false
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_indepth: false
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          config_timezone: Asia/Shanghai
          config_display: large

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update github-metrics.svg - [Skip GitHub Action]
          file_pattern: github-metrics.svg
          # commit_options: '--allow-empty-message'
          # push_options: '--force'
          # skip_dirty_check: true
