name: GitHub Metrics
on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          user: zyqVizzzzz
          token: ${{ secrets.METRICS_TOKEN }}
          output_path: github-metrics.svg
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai

          plugin_introduction: false
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_isocalendar: yes # 年度贡献日历图
          # plugin_habits: yes # 编码习惯
          # plugin_people: yes # 关注者、赞助者等

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update github-metrics.svg - [Skip GitHub Action]
          file_pattern: github-metrics.svg
          # commit_options: '--allow-empty-message'
          # push_options: '--force'
          # skip_dirty_check: true
